name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write
  packages: write
  id-token: write

jobs:
  release-core:
    name: Release core
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v5
        with:
          node-version: 24

      - name: Install dependencies
        run: npm ci

      - name: Release
        working-directory: packages/core
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run release

  release-common:
    name: Release common
    runs-on: ubuntu-latest
    needs: release-core
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v5
        with:
          node-version: 24

      - name: Install dependencies
        run: npm ci

      - name: Release
        working-directory: packages/common
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run release

  release-auth:
    name: Release auth
    runs-on: ubuntu-latest
    needs: release-common
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v5
        with:
          node-version: 24

      - run: git pull origin main

      - name: Install dependencies
        run: npm ci

      - name: Release
        working-directory: packages/auth
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run release

  release-ui:
    name: Release ui
    runs-on: ubuntu-latest
    needs: release-auth
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v5
        with:
          node-version: 24

      - run: git pull origin main

      - name: Install dependencies
        run: npm ci

      - name: Release
        working-directory: packages/ui
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run release